//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18052
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace web136.SLSchedule {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Schedule", Namespace="http://schemas.datacontract.org/2004/07/POCO")]
    [System.SerializableAttribute()]
    public partial class Schedule : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private web136.SLSchedule.Course courseField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string dayField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int enrollmentsField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int idField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string instructorField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string quarterField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int quotaField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string sessionField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string timeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string typeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string yearField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public web136.SLSchedule.Course course {
            get {
                return this.courseField;
            }
            set {
                if ((object.ReferenceEquals(this.courseField, value) != true)) {
                    this.courseField = value;
                    this.RaisePropertyChanged("course");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string day {
            get {
                return this.dayField;
            }
            set {
                if ((object.ReferenceEquals(this.dayField, value) != true)) {
                    this.dayField = value;
                    this.RaisePropertyChanged("day");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int enrollments {
            get {
                return this.enrollmentsField;
            }
            set {
                if ((this.enrollmentsField.Equals(value) != true)) {
                    this.enrollmentsField = value;
                    this.RaisePropertyChanged("enrollments");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int id {
            get {
                return this.idField;
            }
            set {
                if ((this.idField.Equals(value) != true)) {
                    this.idField = value;
                    this.RaisePropertyChanged("id");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string instructor {
            get {
                return this.instructorField;
            }
            set {
                if ((object.ReferenceEquals(this.instructorField, value) != true)) {
                    this.instructorField = value;
                    this.RaisePropertyChanged("instructor");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string quarter {
            get {
                return this.quarterField;
            }
            set {
                if ((object.ReferenceEquals(this.quarterField, value) != true)) {
                    this.quarterField = value;
                    this.RaisePropertyChanged("quarter");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int quota {
            get {
                return this.quotaField;
            }
            set {
                if ((this.quotaField.Equals(value) != true)) {
                    this.quotaField = value;
                    this.RaisePropertyChanged("quota");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string session {
            get {
                return this.sessionField;
            }
            set {
                if ((object.ReferenceEquals(this.sessionField, value) != true)) {
                    this.sessionField = value;
                    this.RaisePropertyChanged("session");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string time {
            get {
                return this.timeField;
            }
            set {
                if ((object.ReferenceEquals(this.timeField, value) != true)) {
                    this.timeField = value;
                    this.RaisePropertyChanged("time");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string type {
            get {
                return this.typeField;
            }
            set {
                if ((object.ReferenceEquals(this.typeField, value) != true)) {
                    this.typeField = value;
                    this.RaisePropertyChanged("type");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string year {
            get {
                return this.yearField;
            }
            set {
                if ((object.ReferenceEquals(this.yearField, value) != true)) {
                    this.yearField = value;
                    this.RaisePropertyChanged("year");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Course", Namespace="http://schemas.datacontract.org/2004/07/POCO")]
    [System.SerializableAttribute()]
    public partial class Course : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string descriptionField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string idField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private web136.SLSchedule.CourseLevel levelField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string titleField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string description {
            get {
                return this.descriptionField;
            }
            set {
                if ((object.ReferenceEquals(this.descriptionField, value) != true)) {
                    this.descriptionField = value;
                    this.RaisePropertyChanged("description");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string id {
            get {
                return this.idField;
            }
            set {
                if ((object.ReferenceEquals(this.idField, value) != true)) {
                    this.idField = value;
                    this.RaisePropertyChanged("id");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public web136.SLSchedule.CourseLevel level {
            get {
                return this.levelField;
            }
            set {
                if ((this.levelField.Equals(value) != true)) {
                    this.levelField = value;
                    this.RaisePropertyChanged("level");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string title {
            get {
                return this.titleField;
            }
            set {
                if ((object.ReferenceEquals(this.titleField, value) != true)) {
                    this.titleField = value;
                    this.RaisePropertyChanged("title");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="CourseLevel", Namespace="http://schemas.datacontract.org/2004/07/POCO")]
    public enum CourseLevel : int {
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        lower = 0,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        upper = 1,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        grad = 2,
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Quota", Namespace="http://schemas.datacontract.org/2004/07/POCO")]
    [System.SerializableAttribute()]
    public partial class Quota : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string course_titleField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int max_studentsField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string schedule_idField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int students_enrolledField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string course_title {
            get {
                return this.course_titleField;
            }
            set {
                if ((object.ReferenceEquals(this.course_titleField, value) != true)) {
                    this.course_titleField = value;
                    this.RaisePropertyChanged("course_title");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int max_students {
            get {
                return this.max_studentsField;
            }
            set {
                if ((this.max_studentsField.Equals(value) != true)) {
                    this.max_studentsField = value;
                    this.RaisePropertyChanged("max_students");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string schedule_id {
            get {
                return this.schedule_idField;
            }
            set {
                if ((object.ReferenceEquals(this.schedule_idField, value) != true)) {
                    this.schedule_idField = value;
                    this.RaisePropertyChanged("schedule_id");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int students_enrolled {
            get {
                return this.students_enrolledField;
            }
            set {
                if ((this.students_enrolledField.Equals(value) != true)) {
                    this.students_enrolledField = value;
                    this.RaisePropertyChanged("students_enrolled");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="SLSchedule.ISLSchedule")]
    public interface ISLSchedule {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISLSchedule/GetScheduleList", ReplyAction="http://tempuri.org/ISLSchedule/GetScheduleListResponse")]
        web136.SLSchedule.GetScheduleListResponse GetScheduleList(web136.SLSchedule.GetScheduleListRequest request);
        
        // CODEGEN: Generating message contract since the operation has multiple return values.
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISLSchedule/GetScheduleList", ReplyAction="http://tempuri.org/ISLSchedule/GetScheduleListResponse")]
        System.Threading.Tasks.Task<web136.SLSchedule.GetScheduleListResponse> GetScheduleListAsync(web136.SLSchedule.GetScheduleListRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISLSchedule/DeleteStudentSchedule", ReplyAction="http://tempuri.org/ISLSchedule/DeleteStudentScheduleResponse")]
        web136.SLSchedule.DeleteStudentScheduleResponse DeleteStudentSchedule(web136.SLSchedule.DeleteStudentScheduleRequest request);
        
        // CODEGEN: Generating message contract since the operation has multiple return values.
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISLSchedule/DeleteStudentSchedule", ReplyAction="http://tempuri.org/ISLSchedule/DeleteStudentScheduleResponse")]
        System.Threading.Tasks.Task<web136.SLSchedule.DeleteStudentScheduleResponse> DeleteStudentScheduleAsync(web136.SLSchedule.DeleteStudentScheduleRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISLSchedule/GetQuota", ReplyAction="http://tempuri.org/ISLSchedule/GetQuotaResponse")]
        web136.SLSchedule.GetQuotaResponse GetQuota(web136.SLSchedule.GetQuotaRequest request);
        
        // CODEGEN: Generating message contract since the operation has multiple return values.
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISLSchedule/GetQuota", ReplyAction="http://tempuri.org/ISLSchedule/GetQuotaResponse")]
        System.Threading.Tasks.Task<web136.SLSchedule.GetQuotaResponse> GetQuotaAsync(web136.SLSchedule.GetQuotaRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISLSchedule/GetSchedule", ReplyAction="http://tempuri.org/ISLSchedule/GetScheduleResponse")]
        web136.SLSchedule.GetScheduleResponse GetSchedule(web136.SLSchedule.GetScheduleRequest request);
        
        // CODEGEN: Generating message contract since the operation has multiple return values.
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISLSchedule/GetSchedule", ReplyAction="http://tempuri.org/ISLSchedule/GetScheduleResponse")]
        System.Threading.Tasks.Task<web136.SLSchedule.GetScheduleResponse> GetScheduleAsync(web136.SLSchedule.GetScheduleRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISLSchedule/UpdateSchedule", ReplyAction="http://tempuri.org/ISLSchedule/UpdateScheduleResponse")]
        web136.SLSchedule.UpdateScheduleResponse UpdateSchedule(web136.SLSchedule.UpdateScheduleRequest request);
        
        // CODEGEN: Generating message contract since the operation has multiple return values.
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISLSchedule/UpdateSchedule", ReplyAction="http://tempuri.org/ISLSchedule/UpdateScheduleResponse")]
        System.Threading.Tasks.Task<web136.SLSchedule.UpdateScheduleResponse> UpdateScheduleAsync(web136.SLSchedule.UpdateScheduleRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISLSchedule/InsertSchedule", ReplyAction="http://tempuri.org/ISLSchedule/InsertScheduleResponse")]
        web136.SLSchedule.InsertScheduleResponse InsertSchedule(web136.SLSchedule.InsertScheduleRequest request);
        
        // CODEGEN: Generating message contract since the operation has multiple return values.
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISLSchedule/InsertSchedule", ReplyAction="http://tempuri.org/ISLSchedule/InsertScheduleResponse")]
        System.Threading.Tasks.Task<web136.SLSchedule.InsertScheduleResponse> InsertScheduleAsync(web136.SLSchedule.InsertScheduleRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISLSchedule/DeleteSchedule", ReplyAction="http://tempuri.org/ISLSchedule/DeleteScheduleResponse")]
        web136.SLSchedule.DeleteScheduleResponse DeleteSchedule(web136.SLSchedule.DeleteScheduleRequest request);
        
        // CODEGEN: Generating message contract since the operation has multiple return values.
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISLSchedule/DeleteSchedule", ReplyAction="http://tempuri.org/ISLSchedule/DeleteScheduleResponse")]
        System.Threading.Tasks.Task<web136.SLSchedule.DeleteScheduleResponse> DeleteScheduleAsync(web136.SLSchedule.DeleteScheduleRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISLSchedule/GetDiscussions", ReplyAction="http://tempuri.org/ISLSchedule/GetDiscussionsResponse")]
        web136.SLSchedule.GetDiscussionsResponse GetDiscussions(web136.SLSchedule.GetDiscussionsRequest request);
        
        // CODEGEN: Generating message contract since the operation has multiple return values.
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISLSchedule/GetDiscussions", ReplyAction="http://tempuri.org/ISLSchedule/GetDiscussionsResponse")]
        System.Threading.Tasks.Task<web136.SLSchedule.GetDiscussionsResponse> GetDiscussionsAsync(web136.SLSchedule.GetDiscussionsRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISLSchedule/createDiscussion", ReplyAction="http://tempuri.org/ISLSchedule/createDiscussionResponse")]
        web136.SLSchedule.createDiscussionResponse createDiscussion(web136.SLSchedule.createDiscussionRequest request);
        
        // CODEGEN: Generating message contract since the operation has multiple return values.
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISLSchedule/createDiscussion", ReplyAction="http://tempuri.org/ISLSchedule/createDiscussionResponse")]
        System.Threading.Tasks.Task<web136.SLSchedule.createDiscussionResponse> createDiscussionAsync(web136.SLSchedule.createDiscussionRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISLSchedule/removeDiscussion", ReplyAction="http://tempuri.org/ISLSchedule/removeDiscussionResponse")]
        web136.SLSchedule.removeDiscussionResponse removeDiscussion(web136.SLSchedule.removeDiscussionRequest request);
        
        // CODEGEN: Generating message contract since the operation has multiple return values.
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISLSchedule/removeDiscussion", ReplyAction="http://tempuri.org/ISLSchedule/removeDiscussionResponse")]
        System.Threading.Tasks.Task<web136.SLSchedule.removeDiscussionResponse> removeDiscussionAsync(web136.SLSchedule.removeDiscussionRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="GetScheduleList", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class GetScheduleListRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public string year;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=1)]
        public string quarter;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=2)]
        public string[] errors;
        
        public GetScheduleListRequest() {
        }
        
        public GetScheduleListRequest(string year, string quarter, string[] errors) {
            this.year = year;
            this.quarter = quarter;
            this.errors = errors;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="GetScheduleListResponse", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class GetScheduleListResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public web136.SLSchedule.Schedule[] GetScheduleListResult;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=1)]
        public string[] errors;
        
        public GetScheduleListResponse() {
        }
        
        public GetScheduleListResponse(web136.SLSchedule.Schedule[] GetScheduleListResult, string[] errors) {
            this.GetScheduleListResult = GetScheduleListResult;
            this.errors = errors;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="DeleteStudentSchedule", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class DeleteStudentScheduleRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public string student_id;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=1)]
        public string schedule_id;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=2)]
        public string[] errors;
        
        public DeleteStudentScheduleRequest() {
        }
        
        public DeleteStudentScheduleRequest(string student_id, string schedule_id, string[] errors) {
            this.student_id = student_id;
            this.schedule_id = schedule_id;
            this.errors = errors;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="DeleteStudentScheduleResponse", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class DeleteStudentScheduleResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public bool DeleteStudentScheduleResult;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=1)]
        public string[] errors;
        
        public DeleteStudentScheduleResponse() {
        }
        
        public DeleteStudentScheduleResponse(bool DeleteStudentScheduleResult, string[] errors) {
            this.DeleteStudentScheduleResult = DeleteStudentScheduleResult;
            this.errors = errors;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="GetQuota", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class GetQuotaRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public string class_id;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=1)]
        public string[] errors;
        
        public GetQuotaRequest() {
        }
        
        public GetQuotaRequest(string class_id, string[] errors) {
            this.class_id = class_id;
            this.errors = errors;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="GetQuotaResponse", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class GetQuotaResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public web136.SLSchedule.Quota GetQuotaResult;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=1)]
        public string[] errors;
        
        public GetQuotaResponse() {
        }
        
        public GetQuotaResponse(web136.SLSchedule.Quota GetQuotaResult, string[] errors) {
            this.GetQuotaResult = GetQuotaResult;
            this.errors = errors;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="GetSchedule", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class GetScheduleRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public int id;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=1)]
        public string[] errors;
        
        public GetScheduleRequest() {
        }
        
        public GetScheduleRequest(int id, string[] errors) {
            this.id = id;
            this.errors = errors;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="GetScheduleResponse", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class GetScheduleResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public web136.SLSchedule.Schedule GetScheduleResult;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=1)]
        public string[] errors;
        
        public GetScheduleResponse() {
        }
        
        public GetScheduleResponse(web136.SLSchedule.Schedule GetScheduleResult, string[] errors) {
            this.GetScheduleResult = GetScheduleResult;
            this.errors = errors;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="UpdateSchedule", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class UpdateScheduleRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public web136.SLSchedule.Schedule s;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=1)]
        public string[] errors;
        
        public UpdateScheduleRequest() {
        }
        
        public UpdateScheduleRequest(web136.SLSchedule.Schedule s, string[] errors) {
            this.s = s;
            this.errors = errors;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="UpdateScheduleResponse", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class UpdateScheduleResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public string[] errors;
        
        public UpdateScheduleResponse() {
        }
        
        public UpdateScheduleResponse(string[] errors) {
            this.errors = errors;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="InsertSchedule", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class InsertScheduleRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public web136.SLSchedule.Schedule s;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=1)]
        public string[] errors;
        
        public InsertScheduleRequest() {
        }
        
        public InsertScheduleRequest(web136.SLSchedule.Schedule s, string[] errors) {
            this.s = s;
            this.errors = errors;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="InsertScheduleResponse", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class InsertScheduleResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public int InsertScheduleResult;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=1)]
        public string[] errors;
        
        public InsertScheduleResponse() {
        }
        
        public InsertScheduleResponse(int InsertScheduleResult, string[] errors) {
            this.InsertScheduleResult = InsertScheduleResult;
            this.errors = errors;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="DeleteSchedule", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class DeleteScheduleRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public int id;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=1)]
        public string[] errors;
        
        public DeleteScheduleRequest() {
        }
        
        public DeleteScheduleRequest(int id, string[] errors) {
            this.id = id;
            this.errors = errors;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="DeleteScheduleResponse", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class DeleteScheduleResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public string[] errors;
        
        public DeleteScheduleResponse() {
        }
        
        public DeleteScheduleResponse(string[] errors) {
            this.errors = errors;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="GetDiscussions", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class GetDiscussionsRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public int class_id;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=1)]
        public string[] errors;
        
        public GetDiscussionsRequest() {
        }
        
        public GetDiscussionsRequest(int class_id, string[] errors) {
            this.class_id = class_id;
            this.errors = errors;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="GetDiscussionsResponse", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class GetDiscussionsResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public web136.SLSchedule.Schedule[] GetDiscussionsResult;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=1)]
        public string[] errors;
        
        public GetDiscussionsResponse() {
        }
        
        public GetDiscussionsResponse(web136.SLSchedule.Schedule[] GetDiscussionsResult, string[] errors) {
            this.GetDiscussionsResult = GetDiscussionsResult;
            this.errors = errors;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="createDiscussion", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class createDiscussionRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public int lecture_id;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=1)]
        public string session;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=2)]
        public int day;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=3)]
        public int time;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=4)]
        public int instructor;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=5)]
        public int quota;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=6)]
        public string[] errors;
        
        public createDiscussionRequest() {
        }
        
        public createDiscussionRequest(int lecture_id, string session, int day, int time, int instructor, int quota, string[] errors) {
            this.lecture_id = lecture_id;
            this.session = session;
            this.day = day;
            this.time = time;
            this.instructor = instructor;
            this.quota = quota;
            this.errors = errors;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="createDiscussionResponse", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class createDiscussionResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public string createDiscussionResult;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=1)]
        public string[] errors;
        
        public createDiscussionResponse() {
        }
        
        public createDiscussionResponse(string createDiscussionResult, string[] errors) {
            this.createDiscussionResult = createDiscussionResult;
            this.errors = errors;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="removeDiscussion", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class removeDiscussionRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public string discussion_id;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=1)]
        public string[] errors;
        
        public removeDiscussionRequest() {
        }
        
        public removeDiscussionRequest(string discussion_id, string[] errors) {
            this.discussion_id = discussion_id;
            this.errors = errors;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="removeDiscussionResponse", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class removeDiscussionResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public bool removeDiscussionResult;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=1)]
        public string[] errors;
        
        public removeDiscussionResponse() {
        }
        
        public removeDiscussionResponse(bool removeDiscussionResult, string[] errors) {
            this.removeDiscussionResult = removeDiscussionResult;
            this.errors = errors;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface ISLScheduleChannel : web136.SLSchedule.ISLSchedule, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class SLScheduleClient : System.ServiceModel.ClientBase<web136.SLSchedule.ISLSchedule>, web136.SLSchedule.ISLSchedule {
        
        public SLScheduleClient() {
        }
        
        public SLScheduleClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public SLScheduleClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public SLScheduleClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public SLScheduleClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        web136.SLSchedule.GetScheduleListResponse web136.SLSchedule.ISLSchedule.GetScheduleList(web136.SLSchedule.GetScheduleListRequest request) {
            return base.Channel.GetScheduleList(request);
        }
        
        public web136.SLSchedule.Schedule[] GetScheduleList(string year, string quarter, ref string[] errors) {
            web136.SLSchedule.GetScheduleListRequest inValue = new web136.SLSchedule.GetScheduleListRequest();
            inValue.year = year;
            inValue.quarter = quarter;
            inValue.errors = errors;
            web136.SLSchedule.GetScheduleListResponse retVal = ((web136.SLSchedule.ISLSchedule)(this)).GetScheduleList(inValue);
            errors = retVal.errors;
            return retVal.GetScheduleListResult;
        }
        
        public System.Threading.Tasks.Task<web136.SLSchedule.GetScheduleListResponse> GetScheduleListAsync(web136.SLSchedule.GetScheduleListRequest request) {
            return base.Channel.GetScheduleListAsync(request);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        web136.SLSchedule.DeleteStudentScheduleResponse web136.SLSchedule.ISLSchedule.DeleteStudentSchedule(web136.SLSchedule.DeleteStudentScheduleRequest request) {
            return base.Channel.DeleteStudentSchedule(request);
        }
        
        public bool DeleteStudentSchedule(string student_id, string schedule_id, ref string[] errors) {
            web136.SLSchedule.DeleteStudentScheduleRequest inValue = new web136.SLSchedule.DeleteStudentScheduleRequest();
            inValue.student_id = student_id;
            inValue.schedule_id = schedule_id;
            inValue.errors = errors;
            web136.SLSchedule.DeleteStudentScheduleResponse retVal = ((web136.SLSchedule.ISLSchedule)(this)).DeleteStudentSchedule(inValue);
            errors = retVal.errors;
            return retVal.DeleteStudentScheduleResult;
        }
        
        public System.Threading.Tasks.Task<web136.SLSchedule.DeleteStudentScheduleResponse> DeleteStudentScheduleAsync(web136.SLSchedule.DeleteStudentScheduleRequest request) {
            return base.Channel.DeleteStudentScheduleAsync(request);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        web136.SLSchedule.GetQuotaResponse web136.SLSchedule.ISLSchedule.GetQuota(web136.SLSchedule.GetQuotaRequest request) {
            return base.Channel.GetQuota(request);
        }
        
        public web136.SLSchedule.Quota GetQuota(string class_id, ref string[] errors) {
            web136.SLSchedule.GetQuotaRequest inValue = new web136.SLSchedule.GetQuotaRequest();
            inValue.class_id = class_id;
            inValue.errors = errors;
            web136.SLSchedule.GetQuotaResponse retVal = ((web136.SLSchedule.ISLSchedule)(this)).GetQuota(inValue);
            errors = retVal.errors;
            return retVal.GetQuotaResult;
        }
        
        public System.Threading.Tasks.Task<web136.SLSchedule.GetQuotaResponse> GetQuotaAsync(web136.SLSchedule.GetQuotaRequest request) {
            return base.Channel.GetQuotaAsync(request);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        web136.SLSchedule.GetScheduleResponse web136.SLSchedule.ISLSchedule.GetSchedule(web136.SLSchedule.GetScheduleRequest request) {
            return base.Channel.GetSchedule(request);
        }
        
        public web136.SLSchedule.Schedule GetSchedule(int id, ref string[] errors) {
            web136.SLSchedule.GetScheduleRequest inValue = new web136.SLSchedule.GetScheduleRequest();
            inValue.id = id;
            inValue.errors = errors;
            web136.SLSchedule.GetScheduleResponse retVal = ((web136.SLSchedule.ISLSchedule)(this)).GetSchedule(inValue);
            errors = retVal.errors;
            return retVal.GetScheduleResult;
        }
        
        public System.Threading.Tasks.Task<web136.SLSchedule.GetScheduleResponse> GetScheduleAsync(web136.SLSchedule.GetScheduleRequest request) {
            return base.Channel.GetScheduleAsync(request);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        web136.SLSchedule.UpdateScheduleResponse web136.SLSchedule.ISLSchedule.UpdateSchedule(web136.SLSchedule.UpdateScheduleRequest request) {
            return base.Channel.UpdateSchedule(request);
        }
        
        public void UpdateSchedule(web136.SLSchedule.Schedule s, ref string[] errors) {
            web136.SLSchedule.UpdateScheduleRequest inValue = new web136.SLSchedule.UpdateScheduleRequest();
            inValue.s = s;
            inValue.errors = errors;
            web136.SLSchedule.UpdateScheduleResponse retVal = ((web136.SLSchedule.ISLSchedule)(this)).UpdateSchedule(inValue);
            errors = retVal.errors;
        }
        
        public System.Threading.Tasks.Task<web136.SLSchedule.UpdateScheduleResponse> UpdateScheduleAsync(web136.SLSchedule.UpdateScheduleRequest request) {
            return base.Channel.UpdateScheduleAsync(request);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        web136.SLSchedule.InsertScheduleResponse web136.SLSchedule.ISLSchedule.InsertSchedule(web136.SLSchedule.InsertScheduleRequest request) {
            return base.Channel.InsertSchedule(request);
        }
        
        public int InsertSchedule(web136.SLSchedule.Schedule s, ref string[] errors) {
            web136.SLSchedule.InsertScheduleRequest inValue = new web136.SLSchedule.InsertScheduleRequest();
            inValue.s = s;
            inValue.errors = errors;
            web136.SLSchedule.InsertScheduleResponse retVal = ((web136.SLSchedule.ISLSchedule)(this)).InsertSchedule(inValue);
            errors = retVal.errors;
            return retVal.InsertScheduleResult;
        }
        
        public System.Threading.Tasks.Task<web136.SLSchedule.InsertScheduleResponse> InsertScheduleAsync(web136.SLSchedule.InsertScheduleRequest request) {
            return base.Channel.InsertScheduleAsync(request);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        web136.SLSchedule.DeleteScheduleResponse web136.SLSchedule.ISLSchedule.DeleteSchedule(web136.SLSchedule.DeleteScheduleRequest request) {
            return base.Channel.DeleteSchedule(request);
        }
        
        public void DeleteSchedule(int id, ref string[] errors) {
            web136.SLSchedule.DeleteScheduleRequest inValue = new web136.SLSchedule.DeleteScheduleRequest();
            inValue.id = id;
            inValue.errors = errors;
            web136.SLSchedule.DeleteScheduleResponse retVal = ((web136.SLSchedule.ISLSchedule)(this)).DeleteSchedule(inValue);
            errors = retVal.errors;
        }
        
        public System.Threading.Tasks.Task<web136.SLSchedule.DeleteScheduleResponse> DeleteScheduleAsync(web136.SLSchedule.DeleteScheduleRequest request) {
            return base.Channel.DeleteScheduleAsync(request);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        web136.SLSchedule.GetDiscussionsResponse web136.SLSchedule.ISLSchedule.GetDiscussions(web136.SLSchedule.GetDiscussionsRequest request) {
            return base.Channel.GetDiscussions(request);
        }
        
        public web136.SLSchedule.Schedule[] GetDiscussions(int class_id, ref string[] errors) {
            web136.SLSchedule.GetDiscussionsRequest inValue = new web136.SLSchedule.GetDiscussionsRequest();
            inValue.class_id = class_id;
            inValue.errors = errors;
            web136.SLSchedule.GetDiscussionsResponse retVal = ((web136.SLSchedule.ISLSchedule)(this)).GetDiscussions(inValue);
            errors = retVal.errors;
            return retVal.GetDiscussionsResult;
        }
        
        public System.Threading.Tasks.Task<web136.SLSchedule.GetDiscussionsResponse> GetDiscussionsAsync(web136.SLSchedule.GetDiscussionsRequest request) {
            return base.Channel.GetDiscussionsAsync(request);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        web136.SLSchedule.createDiscussionResponse web136.SLSchedule.ISLSchedule.createDiscussion(web136.SLSchedule.createDiscussionRequest request) {
            return base.Channel.createDiscussion(request);
        }
        
        public string createDiscussion(int lecture_id, string session, int day, int time, int instructor, int quota, ref string[] errors) {
            web136.SLSchedule.createDiscussionRequest inValue = new web136.SLSchedule.createDiscussionRequest();
            inValue.lecture_id = lecture_id;
            inValue.session = session;
            inValue.day = day;
            inValue.time = time;
            inValue.instructor = instructor;
            inValue.quota = quota;
            inValue.errors = errors;
            web136.SLSchedule.createDiscussionResponse retVal = ((web136.SLSchedule.ISLSchedule)(this)).createDiscussion(inValue);
            errors = retVal.errors;
            return retVal.createDiscussionResult;
        }
        
        public System.Threading.Tasks.Task<web136.SLSchedule.createDiscussionResponse> createDiscussionAsync(web136.SLSchedule.createDiscussionRequest request) {
            return base.Channel.createDiscussionAsync(request);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        web136.SLSchedule.removeDiscussionResponse web136.SLSchedule.ISLSchedule.removeDiscussion(web136.SLSchedule.removeDiscussionRequest request) {
            return base.Channel.removeDiscussion(request);
        }
        
        public bool removeDiscussion(string discussion_id, ref string[] errors) {
            web136.SLSchedule.removeDiscussionRequest inValue = new web136.SLSchedule.removeDiscussionRequest();
            inValue.discussion_id = discussion_id;
            inValue.errors = errors;
            web136.SLSchedule.removeDiscussionResponse retVal = ((web136.SLSchedule.ISLSchedule)(this)).removeDiscussion(inValue);
            errors = retVal.errors;
            return retVal.removeDiscussionResult;
        }
        
        public System.Threading.Tasks.Task<web136.SLSchedule.removeDiscussionResponse> removeDiscussionAsync(web136.SLSchedule.removeDiscussionRequest request) {
            return base.Channel.removeDiscussionAsync(request);
        }
    }
}
