//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18052
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace web136.SLCourse {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Course", Namespace="http://schemas.datacontract.org/2004/07/POCO")]
    [System.SerializableAttribute()]
    public partial class Course : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string descriptionField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string idField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private web136.SLCourse.CourseLevel levelField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string titleField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string description {
            get {
                return this.descriptionField;
            }
            set {
                if ((object.ReferenceEquals(this.descriptionField, value) != true)) {
                    this.descriptionField = value;
                    this.RaisePropertyChanged("description");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string id {
            get {
                return this.idField;
            }
            set {
                if ((object.ReferenceEquals(this.idField, value) != true)) {
                    this.idField = value;
                    this.RaisePropertyChanged("id");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public web136.SLCourse.CourseLevel level {
            get {
                return this.levelField;
            }
            set {
                if ((this.levelField.Equals(value) != true)) {
                    this.levelField = value;
                    this.RaisePropertyChanged("level");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string title {
            get {
                return this.titleField;
            }
            set {
                if ((object.ReferenceEquals(this.titleField, value) != true)) {
                    this.titleField = value;
                    this.RaisePropertyChanged("title");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="CourseLevel", Namespace="http://schemas.datacontract.org/2004/07/POCO")]
    public enum CourseLevel : int {
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        lower = 0,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        upper = 1,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        grad = 2,
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="SLCourse.ISLCourse")]
    public interface ISLCourse {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISLCourse/GetCourseList", ReplyAction="http://tempuri.org/ISLCourse/GetCourseListResponse")]
        web136.SLCourse.Course[] GetCourseList();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISLCourse/GetCourseList", ReplyAction="http://tempuri.org/ISLCourse/GetCourseListResponse")]
        System.Threading.Tasks.Task<web136.SLCourse.Course[]> GetCourseListAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISLCourse/InsertCourse", ReplyAction="http://tempuri.org/ISLCourse/InsertCourseResponse")]
        web136.SLCourse.InsertCourseResponse InsertCourse(web136.SLCourse.InsertCourseRequest request);
        
        // CODEGEN: Generating message contract since the operation has multiple return values.
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISLCourse/InsertCourse", ReplyAction="http://tempuri.org/ISLCourse/InsertCourseResponse")]
        System.Threading.Tasks.Task<web136.SLCourse.InsertCourseResponse> InsertCourseAsync(web136.SLCourse.InsertCourseRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISLCourse/GetCourse", ReplyAction="http://tempuri.org/ISLCourse/GetCourseResponse")]
        web136.SLCourse.GetCourseResponse GetCourse(web136.SLCourse.GetCourseRequest request);
        
        // CODEGEN: Generating message contract since the operation has multiple return values.
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISLCourse/GetCourse", ReplyAction="http://tempuri.org/ISLCourse/GetCourseResponse")]
        System.Threading.Tasks.Task<web136.SLCourse.GetCourseResponse> GetCourseAsync(web136.SLCourse.GetCourseRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISLCourse/DeleteCourse", ReplyAction="http://tempuri.org/ISLCourse/DeleteCourseResponse")]
        web136.SLCourse.DeleteCourseResponse DeleteCourse(web136.SLCourse.DeleteCourseRequest request);
        
        // CODEGEN: Generating message contract since the operation has multiple return values.
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISLCourse/DeleteCourse", ReplyAction="http://tempuri.org/ISLCourse/DeleteCourseResponse")]
        System.Threading.Tasks.Task<web136.SLCourse.DeleteCourseResponse> DeleteCourseAsync(web136.SLCourse.DeleteCourseRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISLCourse/UpdateCourse", ReplyAction="http://tempuri.org/ISLCourse/UpdateCourseResponse")]
        web136.SLCourse.UpdateCourseResponse UpdateCourse(web136.SLCourse.UpdateCourseRequest request);
        
        // CODEGEN: Generating message contract since the operation has multiple return values.
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISLCourse/UpdateCourse", ReplyAction="http://tempuri.org/ISLCourse/UpdateCourseResponse")]
        System.Threading.Tasks.Task<web136.SLCourse.UpdateCourseResponse> UpdateCourseAsync(web136.SLCourse.UpdateCourseRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="InsertCourse", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class InsertCourseRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public web136.SLCourse.Course course;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=1)]
        public string[] errors;
        
        public InsertCourseRequest() {
        }
        
        public InsertCourseRequest(web136.SLCourse.Course course, string[] errors) {
            this.course = course;
            this.errors = errors;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="InsertCourseResponse", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class InsertCourseResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public string InsertCourseResult;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=1)]
        public string[] errors;
        
        public InsertCourseResponse() {
        }
        
        public InsertCourseResponse(string InsertCourseResult, string[] errors) {
            this.InsertCourseResult = InsertCourseResult;
            this.errors = errors;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="GetCourse", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class GetCourseRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public string id;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=1)]
        public string[] errors;
        
        public GetCourseRequest() {
        }
        
        public GetCourseRequest(string id, string[] errors) {
            this.id = id;
            this.errors = errors;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="GetCourseResponse", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class GetCourseResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public web136.SLCourse.Course GetCourseResult;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=1)]
        public string[] errors;
        
        public GetCourseResponse() {
        }
        
        public GetCourseResponse(web136.SLCourse.Course GetCourseResult, string[] errors) {
            this.GetCourseResult = GetCourseResult;
            this.errors = errors;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="DeleteCourse", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class DeleteCourseRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public string id;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=1)]
        public string[] errors;
        
        public DeleteCourseRequest() {
        }
        
        public DeleteCourseRequest(string id, string[] errors) {
            this.id = id;
            this.errors = errors;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="DeleteCourseResponse", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class DeleteCourseResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public string[] errors;
        
        public DeleteCourseResponse() {
        }
        
        public DeleteCourseResponse(string[] errors) {
            this.errors = errors;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="UpdateCourse", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class UpdateCourseRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public web136.SLCourse.Course course;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=1)]
        public string[] errors;
        
        public UpdateCourseRequest() {
        }
        
        public UpdateCourseRequest(web136.SLCourse.Course course, string[] errors) {
            this.course = course;
            this.errors = errors;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="UpdateCourseResponse", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class UpdateCourseResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public string[] errors;
        
        public UpdateCourseResponse() {
        }
        
        public UpdateCourseResponse(string[] errors) {
            this.errors = errors;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface ISLCourseChannel : web136.SLCourse.ISLCourse, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class SLCourseClient : System.ServiceModel.ClientBase<web136.SLCourse.ISLCourse>, web136.SLCourse.ISLCourse {
        
        public SLCourseClient() {
        }
        
        public SLCourseClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public SLCourseClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public SLCourseClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public SLCourseClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public web136.SLCourse.Course[] GetCourseList() {
            return base.Channel.GetCourseList();
        }
        
        public System.Threading.Tasks.Task<web136.SLCourse.Course[]> GetCourseListAsync() {
            return base.Channel.GetCourseListAsync();
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        web136.SLCourse.InsertCourseResponse web136.SLCourse.ISLCourse.InsertCourse(web136.SLCourse.InsertCourseRequest request) {
            return base.Channel.InsertCourse(request);
        }
        
        public string InsertCourse(web136.SLCourse.Course course, ref string[] errors) {
            web136.SLCourse.InsertCourseRequest inValue = new web136.SLCourse.InsertCourseRequest();
            inValue.course = course;
            inValue.errors = errors;
            web136.SLCourse.InsertCourseResponse retVal = ((web136.SLCourse.ISLCourse)(this)).InsertCourse(inValue);
            errors = retVal.errors;
            return retVal.InsertCourseResult;
        }
        
        public System.Threading.Tasks.Task<web136.SLCourse.InsertCourseResponse> InsertCourseAsync(web136.SLCourse.InsertCourseRequest request) {
            return base.Channel.InsertCourseAsync(request);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        web136.SLCourse.GetCourseResponse web136.SLCourse.ISLCourse.GetCourse(web136.SLCourse.GetCourseRequest request) {
            return base.Channel.GetCourse(request);
        }
        
        public web136.SLCourse.Course GetCourse(string id, ref string[] errors) {
            web136.SLCourse.GetCourseRequest inValue = new web136.SLCourse.GetCourseRequest();
            inValue.id = id;
            inValue.errors = errors;
            web136.SLCourse.GetCourseResponse retVal = ((web136.SLCourse.ISLCourse)(this)).GetCourse(inValue);
            errors = retVal.errors;
            return retVal.GetCourseResult;
        }
        
        public System.Threading.Tasks.Task<web136.SLCourse.GetCourseResponse> GetCourseAsync(web136.SLCourse.GetCourseRequest request) {
            return base.Channel.GetCourseAsync(request);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        web136.SLCourse.DeleteCourseResponse web136.SLCourse.ISLCourse.DeleteCourse(web136.SLCourse.DeleteCourseRequest request) {
            return base.Channel.DeleteCourse(request);
        }
        
        public void DeleteCourse(string id, ref string[] errors) {
            web136.SLCourse.DeleteCourseRequest inValue = new web136.SLCourse.DeleteCourseRequest();
            inValue.id = id;
            inValue.errors = errors;
            web136.SLCourse.DeleteCourseResponse retVal = ((web136.SLCourse.ISLCourse)(this)).DeleteCourse(inValue);
            errors = retVal.errors;
        }
        
        public System.Threading.Tasks.Task<web136.SLCourse.DeleteCourseResponse> DeleteCourseAsync(web136.SLCourse.DeleteCourseRequest request) {
            return base.Channel.DeleteCourseAsync(request);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        web136.SLCourse.UpdateCourseResponse web136.SLCourse.ISLCourse.UpdateCourse(web136.SLCourse.UpdateCourseRequest request) {
            return base.Channel.UpdateCourse(request);
        }
        
        public void UpdateCourse(web136.SLCourse.Course course, ref string[] errors) {
            web136.SLCourse.UpdateCourseRequest inValue = new web136.SLCourse.UpdateCourseRequest();
            inValue.course = course;
            inValue.errors = errors;
            web136.SLCourse.UpdateCourseResponse retVal = ((web136.SLCourse.ISLCourse)(this)).UpdateCourse(inValue);
            errors = retVal.errors;
        }
        
        public System.Threading.Tasks.Task<web136.SLCourse.UpdateCourseResponse> UpdateCourseAsync(web136.SLCourse.UpdateCourseRequest request) {
            return base.Channel.UpdateCourseAsync(request);
        }
    }
}
